### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by divineaverage** [divineaverage/P7_Groupomania#3]
Hello! SO I decided to change the profile page to a form, to mimic the Auth page since it's really similar. I then made a mess of things by confusing what to bring over from the Auth component and what to bring over from the profile stuff we did in Card. And now I am mega confused. 

Can this be untangled? Am I at least close? LOL ty in advance

**Comment by divineaverage** [comment]
Welp, assigned this to no one yesterday, super smart. ugh apologies

**Comment by divineaverage** [comment]
Hello! So, after HOURS of trying to get the profile info into the profile page, I've been trying another method. The craziest thing is happening, though. In the profile component, when I first changed all of this, I changed the returned values to "profile.name" and "profile.email." And it worked! (see attached). But then, when I log back in, it errors to this stupid issue reading "name." What the hell is going on? What am I missing?
![Screenshot 2023-06-29 at 9 35 32 PM](https://github.com/divineaverage/P7_Groupomania/assets/107645919/02d114e3-e52f-4cba-b364-ee8a0975a4f5)

**Comment by AccessiT3ch** [comment]
@divineaverage right off the bat, we know that profile is undefined when logging back in, the question then is why 🤔

**Comment by AccessiT3ch** [comment]
@divineaverage aha! Check out what[ your login controller is sending back](https://github.com/divineaverage/P7_Groupomania/blob/main/server/controllers/userCtrl.js#L68-L71), it's not including the user's name. Honestly it might be best to spread the whole user just so you have all the info when they login, so something like:

```js
res.status(200).json({
  ...user,
  userId: user._id,
  token: token,
});
```

**Comment by divineaverage** [comment]
Okay! So fixed that - and it looks like [profileState isn't working here](https://github.com/divineaverage/P7_Groupomania/blob/3e5c78b08ca22321c26076cd71e233380b2a60bb/client/src/components/profile/Profile.jsx#L16C3-L17C67). If I console log store.getState().profile I get back the right info for 2 of the users in the database (see image). So it's on the right track, but something's not quite right. Console logging profileState returns undefined. I feel like this is so close...
![Screenshot 2023-06-30 at 6 39 30 PM](https://github.com/divineaverage/P7_Groupomania/assets/107645919/cc7ad163-d7d0-48c9-b247-7ac7f5f42f82)

**Comment by divineaverage** [comment]
Actually, let's put this aside. Can you check out the Delete Button component for me? Getting a 404, same url I'm using elsewhere that doesn't 404. Just see if there's an easy "duh" there that I'm missing?

**Comment by AccessiT3ch** [comment]
Ah @divineaverage looks like you just need to [update your route in the backend app.js](https://github.com/divineaverage/P7_Groupomania/blob/3e5c78b08ca22321c26076cd71e233380b2a60bb/server/app.js#L53)!

**Comment by AccessiT3ch** [comment]
> Okay! So fixed that - and it looks like [profileState isn't working here](https://github.com/divineaverage/P7_Groupomania/blob/3e5c78b08ca22321c26076cd71e233380b2a60bb/client/src/components/profile/Profile.jsx#L16C3-L17C67). If I console log store.getState().profile I get back the right info for 2 of the users in the database (see image). So it's on the right track, but something's not quite right. Console logging profile still returns undefined. I feel like this is so close...

@divineaverage what is defined on line 16 as `profileState` is the actual profile object, but on line 21 you're treating it like the whole slice state. For the useState for `const [profile, setProfile]`, you can just pass in `profileState` instead of using the `getProfileById` function again. :)

**Comment by divineaverage** [comment]
Fixed, DUH. But - still cannot get to name. It's not getting the name error anymore, which is awesome. And profile isn't undefined anymore! But it still only contains user id and token. Gahhh I feel crazy, I know this is nearly there lol

As for Delete - also fixed and bigger Duh. Still getting the 404 though?

**Comment by AccessiT3ch** [comment]
> @divineaverage what is defined on line 16 as profileState is the actual profile object, but on line 21 you're treating it like the whole slice state. For the useState for const [profile, setProfile], you can just pass in profileState instead of using the getProfileById function again.

@divineaverage it looks like[ this is still an issue](https://github.com/divineaverage/P7_Groupomania/blob/3e5c78b08ca22321c26076cd71e233380b2a60bb/client/src/components/profile/Profile.jsx#L21-L24), your react component state needs to be `const [profile, setProfile] = useState(profileState)`, because `profileState` is the actual profile pulled from your slice by its ID.

**Comment by divineaverage** [comment]
Well, this is weird. It is updated, but not in git for some reason. Just did a new commit and pushed it again.

**Comment by AccessiT3ch** [comment]
@divineaverage it looks like you're not sending the [formSubmission with a body including the updated user](https://github.com/divineaverage/P7_Groupomania/blob/main/client/src/components/profile/Profile.jsx#L65-L69) info. Also be sure your Authorization header is in the `headers` object or wit won't count. I would probably set the body of the request to be something like:

```js
const fetchHeaders = {
  "Content-Type": "application/json",
  Authorization: "Bearer " + userState.token,
};

const fetchBody = { name,  email };

fetch('...', {
  method: "PUT",
  headers: fetchHeaders,
  body: JSON.stringify(fetchBody),
})...
```

**Comment by AccessiT3ch** [comment]
> 2: Getting 401 error on the posts page now too, though it's still working.

This is happening because your Authorization header is outside of the headers object in your fetch requests :)

- [ ] [Delete Button](https://github.com/divineaverage/P7_Groupomania/blob/main/client/src/components/profile/DeleteButton.jsx#L26)
- [ ] [Profile Update](https://github.com/divineaverage/P7_Groupomania/blob/main/client/src/components/profile/Profile.jsx#L68)
- [ ] [Card](https://github.com/divineaverage/P7_Groupomania/blob/main/client/src/components/feed/Card.jsx#L34)
- [x] [Add Post](https://github.com/divineaverage/P7_Groupomania/blob/main/client/src/components/feed/AddPostForm.jsx#L44)
- [x] [Post List](https://github.com/divineaverage/P7_Groupomania/blob/main/client/src/components/feed/PostsList.jsx#L35)

**Comment by divineaverage** [comment]
LOL WHY AM I LIKE THIS? Holy crap. Fixed all 3. Wow. Thank you. Now, delete button makes the server crash - getting "/Users/ljawor/Library/CloudStorage/OneDrive-Hilton/Documents/OC_WebDevPath/P7_Groupomania/server/node_modules/jsonwebtoken/verify.js:171
      return done(new JsonWebTokenError('invalid signature'));
                  ^
JsonWebTokenError: invalid signature"

**Comment by divineaverage** [comment]
Also THANK YOU, can't say it enough lol

**Comment by AccessiT3ch** [comment]
@divineaverage haha, don't worry about it, this is totally normal when crunching for a deadline (which happens a lot in real world!) we start to rush and then we get tired and we miss things, it's the toll of stress! The trick is to slow down enough to self-care enough to keep yourself fresh, AND TO GIVE YOURSELF SOME GRACE, often I find this looks like lots of little breaks to recenter (though I am notoriously bad at it, ha)!

On top of that, you are/have been sick enough to send you to surgery in a few days, which nicely coincides with your current funding deadline, which is just more stress, and so the cycle continues. 

All that being said, you are doing great, just a little more to go!

**Comment by AccessiT3ch** [comment]
@divineaverage It looks like you're still trying to verify/authorize tokens in your delete controller, but we don't need to do manually do that because it should be handled via the middleware. I'm not sure if this error is coming from the middleware or controller, so just make sure:
- [ ] to remove the jwt logic in your [back-end controller](https://github.com/divineaverage/P7_Groupomania/blob/main/server/controllers/userCtrl.js#L145-L146)
- [ ] the token is defined in the front-end fetch network request
- [ ] the userId (needed to find the user to destroy) is defined in the back end controller
